### PR TITLE
Something 

### PR DESCRIPTION
**Pull request by xjussix**
asdasd

### CODE REVIEW

**Comment by xjussix** [comment]
[Add payment link tracking](https://trello.com/c/tA8W9znJ/3-add-payment-link-tracking)

**Comment by xjussix** [comment]
[Add payment link tracking](https://trello.com/c/tA8W9znJ/3-add-payment-link-tracking)

**Comment by xjussix** [comment]
[Add payment link tracking](https://trello.com/c/tA8W9znJ/3-add-payment-link-tracking)

**Comment by janneh** [comment]
Comment....

**Comment by xjussix** [comment]
[Add payment link tracking](https://trello.com/c/tA8W9znJ/3-add-payment-link-tracking)

**Comment by xjussix** [comment]
[Add payment link tracking](https://trello.com/c/tA8W9znJ/3-add-payment-link-tracking)

**Comment by xjussix** [comment]
[Add payment link tracking](https://trello.com/c/tA8W9znJ/3-add-payment-link-tracking)

**Comment by xjussix** [comment]
[Add payment link tracking](https://trello.com/c/tA8W9znJ/3-add-payment-link-tracking)

**Comment by xjussix** [comment]
[Add payment link tracking](https://trello.com/c/tA8W9znJ/3-add-payment-link-tracking)

**Pull request closed without merging**
